
spring:
  profiles:
    # 默认激活 dev 环境
    active: dev


jwt:
  # 签发人测试，废弃
  issuer: quanxiaoha
  # 秘钥测试，废弃
  secret: kYGV849e7QbjkbzV8O5kN8NvrYa4OJjU/NDf9672LRrF795x/e4luCKllSnukz/c4xnRLH9sdeSjFVyaYxKwdg==

  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer